Add REQUIRES postgres to tests/utils/installation.shtest test
If postgresql isn't installed on the test machine this test fails
during the attempt to build the psycopg2 package with error:
Error: pg_config executable not found.