Install missing mypy stubs
Mypy currently warns about missing stubs to analyse LNT's code:
lnt/server/ui/globals.py:5: error: Library stubs not installed for
"flask" (or incompatible with Python 2.7)
lnt/server/ui/decorators.py:1: error: Library stubs not installed for
"flask" (or incompatible with Python 2.7)
lnt/lnttool/convert.py:2: error: Library stubs not installed for "click"
(or incompatible with Python 2.7)
lnt/lnttool/common.py:2: error: Library stubs not installed for "click"
(or incompatible with Python 2.7)
lnt/lnttool/import_report.py:1: error: Library stubs not installed for
"click" (or incompatible with Python 2.7)
lnt/lnttool/admin.py:4: error: Library stubs not installed for "click"
(or incompatible with Python 2.7)

This commits adds the necessary dependency to get rid of those warnings.

Reviewed By: PrzemekWirkus

Differential Revision: https://reviews.llvm.org/D104706