[LNT] Pin Python version in Dockerfile to 3.7 temporarily
Python 3.9 has been released and one of the dependencies of LNT does not compiler under it.  pyyaml seems to fail during building:

```
 ext/_yaml.c: In function '__Pyx_modinit_type_init_code':
    ext/_yaml.c:25698:25: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'
    25698 |   __pyx_type_5_yaml_Mark.tp_print = 0;
          |                         ^
    ext/_yaml.c:25718:28: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'
    25718 |   __pyx_type_5_yaml_CParser.tp_print = 0;
          |                            ^
    ext/_yaml.c:25732:29: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'
    25732 |   __pyx_type_5_yaml_CEmitter.tp_print = 0;
          |                             ^
```

Presumably because the header has changed under python 3.9.  For now let's pin the Dockerfile to 3.7 until this is sorted so LNT can still run.

Reviewed By: thopre

Differential Revision: https://reviews.llvm.org/D89377