Pin Jinja2 to 2.11.3
8fc27f472c22fe64a838e4e6cc9421996c4fb2c1 pinned MarkupSafe to
1.1.1, which lead to this error on our buildbots that are using
Python 3.10 to run the lnt client:
error: MarkupSafe 1.1.1 is installed but MarkupSafe>=2.0 is required by {'Jinja2'}

Jinja2 2.11.3 is the last version that will work with that version of
MarkupSafe:
https://github.com/pallets/jinja/blob/2.11.3/setup.py

The 3.x series moved to >= 2.0.0:
https://github.com/pallets/jinja/blob/3.0.0rc1/setup.py