Bump dependencies to get working on Python 3.12 (#22)
This bumps some dependencies so that they no longer use the old collections module, which fixes errors like this on Python 3.12 (and possibly earlier?)

    ImportError: cannot import name 'Container' from 'collections'

After this I was able to get lnt running via

    $ python -m venv venv
    $ source venv/bin/activate
    $ pip install setuptools
    $ python setup.py develop
    $ python -m lnt.lnttool.main --version

I only bumped the packages as much as needed, so they're not fully up-to-date.