Don't add objects to the logger, only strings.
When objects are added to the logger, the mem_logger apparantly could
retain those. If then the object isn't picklable, during submission of
results, the server could crash with a backtrace like the following, as
a the mem_logger is given to the python multiprocessing manager, which
needs all objects to be picklable.

....
  File "/lnt/lnt/util/async_ops.py", line 40, in launch_workers
    current_app.config['mem_logger'].buffer =
manager.list(current_app.config['mem_logger'].buffer)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 567, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 101, in dispatch
    c.send((id, methodname, args, kwds))
PicklingError: Can't pickle <class 'lnt.server.db.testsuitedb.Run'>:
attribute lookup lnt.server.db.testsuitedb.Run failed

llvm-svn: 261531