[Docs] Use `db_default` instead of `default` in example submit url.
Summary:
It looks like the URL changed. With `default` I get the following error:

    127.0.0.1 - - [25/Oct/2017 15:09:36] "POST /default/submitRun HTTP/1.1" 404 -
    error: lnt server: The page you are looking for does not exist.

Reviewers: kristof.beyls, MatzeB

Reviewed By: MatzeB

Subscribers: llvm-commits

Differential Revision: https://reviews.llvm.org/D39291

llvm-svn: 316746